"""Shared types and infrastructure for manga-translator services."""

from .config import (
    Config,
    Context,
    Alignment,
    Colorizer,
    ColorizerConfig,
    Detector,
    DetectorConfig,
    Direction,
    Inpainter,
    InpainterConfig,
    InpaintPrecision,
    Ocr,
    OcrConfig,
    Renderer,
    RenderConfig,
    Translator,
    TranslatorConfig,
    Upscaler,
    UpscaleConfig,
    LANGUAGE_ORIENTATION_PRESETS,
    VALID_LANGUAGES,
)
